### ISSUE TITLE
Endless reboot on ESP-12E and WeMos D1 Mini

### ISSUE THREAD

**Issue by stripu** [OpenSprinkler/OSBeeWiFi-Firmware#1]
Hi Ray!

First of all, let me congratulate you on creating such a beautiful product! It's simple, yet powerful.
Now, I'm encountering some issues: I've tried to compile and upload the firmware to an ESP-12E and a WeMos D1 Mini, in order to try out the web interface and such. The compilation is flawless, but after the upload, my devices go in a boot loop, and this is what i'm seeing in the Serial Monitor:

ets Jan  8 2013,rst cause:2, boot mode:(3,7)
load 0x4010f000, len 1264, room 16 
tail 0
chksum 0x0f
csum 0x0f
~ld

I've tried powering the devices with different power supplies, thinking they might not get enough power, but to no avail.
Am I missing something? Is there any additional hardware that's needed in order for the firmware to boot properly, or should i be able to flash it to a barebone ESP-12E and it should work without issues?

Thanks for your time, and I hope you'll excuse my noobness if it's something i'm missing, as I'm still learning.. :)

**Comment by TeguhTeknisi** [comment]
Hi,
I try this using Lolin Node MCU (clone) and its work.
I use Arduino 1.8.3, choose "NodeMCU 1.0 (ESP-12E Module)"
I have little problem, its "hang" after i connect to my TP Link AP MR3220
After i press Reset on the NodeMCU, its work.
I Will try it to my Wemos D1 Mini tomorrow.
Here the screenshot: https://user-images.githubusercontent.com/32675055/31678388-3b0bceec-b398-11e7-83e2-2a0eac7b9ba8.jpg


Here from serial monitor.
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v3de0c112
~ld
⸮RTC detected
saving config file...ok
create program data...
ok
server started @ 80
scan network
AP mode
192.168.4.1
saving config file...ok
STA mode with AP
saving config file...ok

 ets Jan  8 2013,rst cause:2, boot mode:(1,7)


 ets Jan  8 2013,rst cause:4, boot mode:(1,7)

wdt reset
s$

**Comment by TeguhTeknisi** [comment]
Hi, 
I want to tell you, i can compile and upload to Wemos D1 Mini ( a clone )

Here the Serial Info:
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0
RTC detected
loading config file...ok
server started @ 80
scan network
AP mode
192.168.4.1

**Comment by stripu** [comment]
Hi @TeguhTeknisi ! Thanks for your response! So i guess there might be something wrong with my IDE. Btw: are you using the ArduinoExample file, or are you compiling the fw from the Makefile?
Regards

**Comment by TeguhTeknisi** [comment]
Hi @stripu 
I use Arduino -> Examples -> OSBeeWiFi -> mainArduino
I choose Board: "WeMos D1 R2 & mini"
Flash Size: "4M (1M SPIFFS)"  

i use esp8266 v2.3.0 , but i modified updater.h in ~/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266/
Using from here https://github.com/OpenGarage/OpenGarage-Firmware/blob/master/Modifications/Updater.h
Somehow, The Updater.h from here https://github.com/OpenSprinkler/OSBeeWiFi-Firmware/tree/master/Modifications will make Compile Failed.

I use Kubuntu 17.04 OS 64bit, and Arduino 1.8.3 64bit

I hope this will help you.

**Comment by stripu** [comment]
Yes!! Success. It was the Updater.h file, throwing out errors. I used the one provided and it works properly. Thanks!
