### ISSUE TITLE
Error compiling using Arduino IDE

### ISSUE THREAD

**Issue by acca84** [OpenSprinkler/OSBeeWiFi-Firmware#3]
Hello, i downloaded OSBeeWifi firmware in order to flash it on an esp8266

I had to modify fonts.h and images.h in order to make it work with SSD1306 library (changing font and logos datatype)
To modify  call to blynk begin() function main.cpp : 
Blynk.begin(osb.options[OPTION_AUTH].sval.c_str(),osb.options[OPTION_SSID].sval.c_str(),osb.options[OPTION_PASS].sval.c_str());
Modify updater.h

But there is a compilation error i can't solve : 

> Archiving built core (caching) in: C:\Users\Acca\AppData\Local\Temp\arduino_cache_905034\core\core_esp8266_esp8266_generic_CpuFrequency_80,FlashFreq_40,FlashMode_dio,UploadSpeed_9600,FlashSize_4M3M,ResetMethod_ck,Debug_Disabled,DebugLevel_None_____e92e35acb2bb2c88dd1ba926ed261c45.a
> libraries\OSBeeWiFi\main.cpp.o: In function `std::_Function_handler<void (), void(*))>::_M_invoke(std::_Any_data const&)':
> 
> C:\Users\Acca\Documents\Arduino\libraries\esp8266-oled-ssd1306/SSD1306Wire.h:134: multiple definition of `Blynk'
> 
> sketch\opensprinkler.ino.cpp.o:(.bss.Blynk+0x0): first defined here
> 
> collect2.exe: error: ld returned 1 exit status
> 
> exit status 1
> Erreur de compilation pour la carte Generic ESP8266 Module
i can't find the "blynk" term in SSD1306Wire.h
Could someone help me please ?

**Comment by acca84** [comment]
Hello, i downloaded OSBeeWifi firmware in order to flash it on an esp8266

I had to modify fonts.h and images.h in order to make it work with SSD1306 library (changing font and logos datatype)
To modify call to blynk begin() function main.cpp :
Blynk.begin(osb.options[OPTION_AUTH].sval.c_str(),osb.options[OPTION_SSID].sval.c_str(),osb.options[OPTION_PASS].sval.c_str());
Modify updater.h

But there is a compilation error i can't solve :

    Archiving built core (caching) in: C:\Users\Acca\AppData\Local\Temp\arduino_cache_905034\core\core_esp8266_esp8266_generic_CpuFrequency_80,FlashFreq_40,FlashMode_dio,UploadSpeed_9600,FlashSize_4M3M,ResetMethod_ck,Debug_Disabled,DebugLevel_None_____e92e35acb2bb2c88dd1ba926ed261c45.a
    libraries\OSBeeWiFi\main.cpp.o: In function `std::_Function_handler<void (), void(*))>::_M_invoke(std::_Any_data const&)':

    C:\Users\Acca\Documents\Arduino\libraries\esp8266-oled-ssd1306/SSD1306Wire.h:134: multiple definition of `Blynk'

    sketch\opensprinkler.ino.cpp.o:(.bss.Blynk+0x0): first defined here

    collect2.exe: error: ld returned 1 exit status

    exit status 1
    Erreur de compilation pour la carte Generic ESP8266 Module
    i can't find the "blynk" term in SSD1306Wire.h
    Could someone help me please ?

**Comment by rayshobby** [comment]
I would suggest using the makefile. I haven't used Arduino for a long time and to compile the code you do not need to use the Arduino IDE.
