### ISSUE TITLE
API documentation error in /jo solenoid type

### ISSUE THREAD

**Issue by vanossj** [OpenSprinkler/OSBeeWiFi-Firmware#4]
OSBeeAPI 1.0.0 doc says that the _Get Options (jo)_ endpoint returns json object with
```sot: solenoid type. 0: non-latching (default); 1: latching.```

I think this is incorrect and should be swapped. The code in [settings.html](https://github.com/OpenSprinkler/OSBeeWiFi-Firmware/blob/master/OSBeeWiFi/html/settings.html#L37) has the solenoid options as 0 for non-latching, 1 for latching.

Then it will be consistent with the _Get Controller Variables (jc)_ endpoint
```sot: solenoid type. 0: latching (default); 1: non-latching```

**Comment by rayshobby** [comment]
Thanks. This is indeed a typo. It will be corrected in the document shortly.
