### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by afagard** [OpenSprinkler/OSBeeWiFi-Firmware#5]
Using the latest esp8266 build this lib does not compile. The changes to `Updater.h` in the modifications folder are no longer valid. In general, I would like to add that changing core files should never be done for this reason.

It also seems that there is an error regarding this library's compatibility to the display library. Perhaps there was an update that broke some code.

**Comment by rayshobby** [comment]
The firmware code has been updated and no longer requires the modification to existing libraries.
